# Generated by Django 4.2.7 on 2023-11-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='air_line',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
