# Generated by Django 4.2.7 on 2024-01-08 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10)),
                ('cost', models.FloatField()),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Visiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('passport', models.CharField(max_length=30)),
                ('fr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiters_from', to='system.city')),
            ],
        ),
        migrations.CreateModel(
            name='Living',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='living_who', to='system.room')),
                ('visiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='living_where', to='system.visiter')),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('mn', 'mn'), ('tu', 'tu'), ('we', 'we'), ('th', 'th'), ('fr', 'fr'), ('sa', 'sa'), ('su', 'su')], max_length=10)),
                ('clearer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearing_where', to='system.worker')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clearing_who', to='system.floor')),
            ],
        ),
    ]
