# Generated by Django 4.2.7 on 2024-01-10 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_living_room_alter_living_visiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='living',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='living_who', to='system.room'),
        ),
        migrations.AlterField(
            model_name='living',
            name='visiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='living_where', to='system.visiter'),
        ),
    ]
