# Generated by Django 4.2.6 on 2023-10-22 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 22, 3, 45, 0, 955791)),
        ),
        migrations.AddField(
            model_name='owner',
            name='first_name',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='owner',
            name='last_name',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
