# Generated by Django 4.2.6 on 2023-10-22 01:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_owner_birthday_owner_first_name_owner_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverslicense',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='owner',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 22, 4, 27, 26, 284159)),
        ),
        migrations.AlterField(
            model_name='owner',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
