# Generated by Django 4.2.2 on 2023-10-22 13:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_first_app', '0003_alter_car_id_alter_driverslicense_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='home_address',
            field=models.CharField(default='------', max_length=50),
        ),
        migrations.AddField(
            model_name='owner',
            name='nationality',
            field=models.CharField(default='------', max_length=20),
        ),
        migrations.AddField(
            model_name='owner',
            name='passport_number',
            field=models.CharField(default='------', max_length=8),
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owner',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 22, 16, 43, 0, 20555)),
        ),
    ]
